Repository Geek-Collectors-Network/geek-collectors-network, pull requests merged in 2024-03, with the labels that each got.

#115 114 Remove `LoginControls` from registration page
  apps/frontend/src/components/LoginForm.tsx
  apps/frontend/src/components/RegistrationForm.tsx
  apps/frontend/src/schemas/schemas.ts
Labels: Chore

#110 Define resources as a seperate Docker stack
  apps/api/.env.example
  docker-compose.yml
  makefile
Labels: Feature

#142 Fix api response corruption
  .vscode/launch.json
  apps/api/package.json
  docker/Dockerfile.backend
  package-lock.json
Labels: Bug

#146 chore: update schema
  apps/api/drizzle/0000_hot_jimmy_woo.sql
  apps/api/drizzle/0000_overrated_fabian_cortez.sql
  apps/api/drizzle/0001_naive_rocket_racer.sql
  apps/api/drizzle/meta/0000_snapshot.json
  apps/api/drizzle/meta/0001_snapshot.json
  apps/api/drizzle/meta/_journal.json
  apps/api/src/index.ts
  apps/api/src/models/dummy.ts
  apps/api/src/models/schema.ts
  apps/api/src/server/services/AuthService.ts
  apps/api/src/server/services/Service.ts
  apps/api/src/server/services/TestService.ts
  apps/api/src/server/services/UserService.ts
Labels: Chore

#170 feat(db): add item models to schema
  apps/api/src/models/schema.ts
Labels: Feature
